export const INDUSTRY_OPTIONS = [
  { value: 'accounting_finance', label: 'Accounting & Finance' },
  { value: 'advertising', label: 'Advertising' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'architecture', label: 'Architecture' },
  { value: 'art_design', label: 'Art & Design' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'aviation', label: 'Aviation' },
  { value: 'banking', label: 'Banking' },
  { value: 'bar_nightclub', label: 'Bar & Nightclub' },
  { value: 'beauty_cosmetics', label: 'Beauty & Cosmetics' },
  { value: 'books_literature', label: 'Books & Literature' },
  { value: 'business_consulting', label: 'Business & Consulting' },
  { value: 'childcare', label: 'Childcare' },
  { value: 'cleaning_maintenance', label: 'Cleaning & Maintenance' },
  { value: 'clothing', label: 'Clothing' },
  { value: 'communications', label: 'Communications' },
  { value: 'community_non_profit', label: 'Community & Non-profit' },
  { value: 'computer_electronics', label: 'Computer & Electronics' },
  { value: 'construction', label: 'Construction' },
  { value: 'dating', label: 'Dating' },
  { value: 'design', label: 'Design' },
  { value: 'drinks', label: 'Drinks' },
  { value: 'economics', label: 'Economics' },
  { value: 'education', label: 'Education' },
  { value: 'engineering', label: 'Engineering' },
  { value: 'entertainment', label: 'Entertainment' },
  { value: 'entrepreneurship', label: 'Entrepreneurship' },
  { value: 'environment', label: 'Environment' },
  { value: 'events', label: 'Events' },
  { value: 'fashion', label: 'Fashion' },
  { value: 'fitness_wellness', label: 'Fitness & wellness' },
  { value: 'floral', label: 'Floral' },
  { value: 'food', label: 'Food' },
  { value: 'footwear', label: 'Footwear' },
  { value: 'gambling', label: 'Gambling' },
  { value: 'games', label: 'Games' },
  { value: 'health', label: 'Health' },
  { value: 'hobbies_recreation', label: 'Hobbies & Recreation' },
  { value: 'home_garden', label: 'Home & Garden' },
  { value: 'industrial', label: 'Industrial' },
  { value: 'internet', label: 'Internet' },
  { value: 'law', label: 'Law' },
  { value: 'management', label: 'Management' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'medical_pharmaceutical', label: 'Medical & Pharmaceutical' },
  { value: 'movies', label: 'Movies' },
  { value: 'music', label: 'Music' },
  { value: 'news', label: 'News' },
  { value: 'nursing', label: 'Nursing' },
  { value: 'pets_animals', label: 'Pets & Animals' },
  { value: 'photography', label: 'Photography' },
  { value: 'political', label: 'Political' },
  { value: 'real_estate', label: 'Real estate' },
  { value: 'real_estate_mortgage', label: 'Real Estate & Mortgage' },
  { value: 'religious', label: 'Religious' },
  { value: 'restaurant_cuisine', label: 'Restaurant & Cuisine' },
  { value: 'retail', label: 'Retail' },
  { value: 'science', label: 'Science' },
  { value: 'security', label: 'Security' },
  { value: 'shopping', label: 'Shopping' },
  { value: 'small_business', label: 'Small business' },
  { value: 'sports', label: 'Sports' },
  { value: 'technology', label: 'Technology' },
  { value: 'toys', label: 'Toys' },
  { value: 'travel_hotel', label: 'Travel & Hotel' },
  { value: 'wedding', label: 'Wedding' },
];

export const EMOTION_OPTIONS = [
  { value: 'happy', label: 'Happy' },
  { value: 'excited', label: 'Excited' },
  { value: 'surprised', label: 'Surprised' },
  { value: 'smart', label: 'Smart' },
  { value: 'love', label: 'Love' },
  { value: 'cool', label: 'Cool' },
  { value: 'curious', label: 'Curious' },
  { value: 'trust', label: 'Trust' },
  { value: 'secret', label: 'Secret' },
  { value: 'neutral', label: 'Neutral' },
  { value: 'desire', label: 'Desire' },
  { value: 'tired', label: 'Tired' },
  { value: 'angry', label: 'Angry' },
  { value: 'bored', label: 'Bored' },
  { value: 'sad', label: 'Sad' },
  { value: 'fear', label: 'Fear' },
  { value: 'crying', label: 'Crying' },
];
