/** Map each flow to its section title */
export const FLOW_TITLES = {
  'designs-from-prompt': 'Generated Design Variations',
  'designs-from-content': 'Generated Design Variations',
  'content-from-prompt': 'Generated Content',
  'get-design-variants': 'Design Variants',
  'request-status': 'Request Status',
  'list-brands': 'Brand Result',
  'create-brand': 'Brand Result',
  'extract-brand': 'Extracted Brand Details',
  'set-default-brand': 'Brand Result',
  'archive-brand': 'Brand Result',
  'update-brand': 'Brand Result',
  'get-media': 'Media',
  'create-media': 'Media Result',
  'update-media': 'Media Result',
  'delete-media': 'Media Result',
  'generate-media': 'Media Result',
  'get-presigned-url': 'Presigned URL',
  'get-fonts': 'Font Result',
  'upload-fonts': 'Font Upload',
  'login-user': 'User Login Response',
  'delete-user': 'User Delete Response',
  'set-user-credit-limit': 'Credit Limit Response',
};
